### Register user
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstName": "Carlos",
  "lastName": "Alberto",
  "email": "carlos.alberto@nexbank.com",
  "phoneNumber": "5512345678",
  "password": "Password123!",
  "birthDate": "1995-06-15"
}